### PR TITLE
Update CSS guidelines

### PR DESCRIPTION
**Pull request by iamdarrenhall**
@andrewbrandwood @bmds @furzeface 

I've been through and updated the CSS guidelines, and included the name-spacing and links to more info about it. It's probably best to [view the file directly](https://github.com/code-computerlove/frontend-guidelines/blob/css-2016/FE-guidelines-CSS.md#directory-structure) rather than going through the changes below.

Looking forward to some discussion on it!

### CODE REVIEW

**Comment by furzeface** [comment]
Where's the crazy alphabetisation @iamdarrenhall :yum:

**Comment by bmds** [comment]
I agree with @furzeface we're missing the alphabetisation rules.

I agree with the normalize statement for the time being. Long term i think we should look to pull it out into npm or similar to highlight that it is an outside dependency. Same with the tools and mixins, the ones there will be site specific and we pull in the generic ones from outside.

**Comment by furzeface** [comment]
Yeah I'm a big fan of having it as a bower or NPM dependency. 

One of my **huge** pet hates is 3rd-party code in the repository when it can just be a managed dependency!

**Comment by iamdarrenhall** [comment]
Yeah I'm happy for that to be the case, maybe once we get the slate-sass or whatever, we can be more specific about what is what.

**Comment by andrewbrandwood** [comment]
Petty little thing, can we use the terminology good/bad over wrong/right ?  it's easier to talk through. It gives it context to our standards. Wrong/Right (when spoken) suggests that it won't work at all.

**Comment by iamdarrenhall** [comment]
No problem, I've updated them.

**Pull request merged**
